version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/awstechyp/
hooks:
  BeforeInstall:
    - location: TechypPHP/Deploy/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: TechypPHP/Deploy/restart_server
      timeout: 300
      runas: ubuntu
